name: tt-backend-docker

services:

  tt-pg:
    image: postgres:17.2
    container_name: tt-pg
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_EXTERN}:${DB_PORT}"
    networks:
      - internal
    volumes:
      - tt-pg-disk:/var/lib/postgresql/data
    restart: unless-stopped

  tt-minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: tt-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "${MINIO_PORT_API_EXTERN}:${MINIO_PORT_API}"
      - "${MINIO_PORT_WEB_EXTERN}:${MINIO_PORT_WEB}"
    networks:
      - internal
    volumes:
      - tt-minio-disk:/data
    restart: unless-stopped
    command: server --console-address ":${MINIO_PORT_WEB}" /data


  tt-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tt-backend
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PORT_API=${MINIO_PORT_API}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - tt-pg


volumes:
  tt-pg-disk:
  tt-minio-disk:

networks:
  internal: