name: tt-backend-docker

services:

  tt-pg:
    image: postgres:17.2
    container_name: tt-pg
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT_EXTERN}:5432"
    networks:
      - internal
    volumes:
      - tt-pg-disk:/var/lib/postgresql/data
    restart: unless-stopped

  tt-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tt-backend
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - tt-pg


volumes:
  tt-pg-disk:

networks:
  internal: