name: Tag Track Backend Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  go-tt-backend-tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: [1.23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v --race